// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_ops_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldClientOpsLogs = `-- name: DeleteOldClientOpsLogs :execrows
DELETE FROM client_ops_logs
WHERE id IN (
    SELECT id FROM client_ops_logs
    WHERE created_at < now() - interval '30 days'
    ORDER BY id ASC
    LIMIT $1::bigint
)
`

func (q *Queries) DeleteOldClientOpsLogs(ctx context.Context, dollar_1 int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldClientOpsLogs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertClientOpsLog = `-- name: InsertClientOpsLog :one
INSERT INTO client_ops_logs (id, user_id, device, app_version, events, client_sent_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertClientOpsLogParams struct {
	ID           string             `json:"id"`
	UserID       string             `json:"userId"`
	Device       string             `json:"device"`
	AppVersion   string             `json:"appVersion"`
	Events       []byte             `json:"events"`
	ClientSentAt pgtype.Timestamptz `json:"clientSentAt"`
}

func (q *Queries) InsertClientOpsLog(ctx context.Context, arg InsertClientOpsLogParams) (string, error) {
	row := q.db.QueryRow(ctx, insertClientOpsLog,
		arg.ID,
		arg.UserID,
		arg.Device,
		arg.AppVersion,
		arg.Events,
		arg.ClientSentAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
