// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUserMcpEntries = `-- name: ListUserMcpEntries :many
SELECT
    d.record_date,
    COALESCE(NULLIF(TRIM(u.nickname), ''), '家人')::text AS nickname,
    COALESCE(de.record_time, de.created_at) AS record_at,
    COALESCE(NULLIF(TRIM(de.address), ''), NULLIF(TRIM(de.detail_address), ''), '')::text AS location,
    COALESCE(NULLIF(TRIM(de.text), ''), '')::text AS text
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
JOIN users u ON u.id = de.created_by
WHERE d.user_id = $1
  AND d.record_date >= $2::date
  AND d.record_date <= $3::date
ORDER BY d.record_date DESC, record_at DESC
LIMIT $4
`

type ListUserMcpEntriesParams struct {
	UserID  string      `json:"userId"`
	Column2 pgtype.Date `json:"column2"`
	Column3 pgtype.Date `json:"column3"`
	Limit   int32       `json:"limit"`
}

type ListUserMcpEntriesRow struct {
	RecordDate pgtype.Date        `json:"recordDate"`
	Nickname   string             `json:"nickname"`
	RecordAt   pgtype.Timestamptz `json:"recordAt"`
	Location   string             `json:"location"`
	Text       string             `json:"text"`
}

func (q *Queries) ListUserMcpEntries(ctx context.Context, arg ListUserMcpEntriesParams) ([]ListUserMcpEntriesRow, error) {
	rows, err := q.db.Query(ctx, listUserMcpEntries,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMcpEntriesRow{}
	for rows.Next() {
		var i ListUserMcpEntriesRow
		if err := rows.Scan(
			&i.RecordDate,
			&i.Nickname,
			&i.RecordAt,
			&i.Location,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
