// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (id, user_id, record_time, record_date, title, content, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, user_id, record_time, record_date, title, content, created_at
`

type CreateMemoryParams struct {
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	RecordTime pgtype.Timestamptz `json:"recordTime"`
	RecordDate pgtype.Date        `json:"recordDate"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.ID,
		arg.UserID,
		arg.RecordTime,
		arg.RecordDate,
		arg.Title,
		arg.Content,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordTime,
		&i.RecordDate,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memories WHERE id = $1 AND user_id = $2
`

type DeleteMemoryParams struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMemoriesByDateRange = `-- name: ListMemoriesByDateRange :many
SELECT
    record_time AS created_at,
    title,
    content
FROM memories
WHERE user_id = $1
  AND record_date >= $2::date
  AND record_date <= $3::date
ORDER BY record_time DESC
LIMIT $4
`

type ListMemoriesByDateRangeParams struct {
	UserID  string      `json:"userId"`
	Column2 pgtype.Date `json:"column2"`
	Column3 pgtype.Date `json:"column3"`
	Limit   int32       `json:"limit"`
}

type ListMemoriesByDateRangeRow struct {
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
}

func (q *Queries) ListMemoriesByDateRange(ctx context.Context, arg ListMemoriesByDateRangeParams) ([]ListMemoriesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesByDateRange,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoriesByDateRangeRow{}
	for rows.Next() {
		var i ListMemoriesByDateRangeRow
		if err := rows.Scan(&i.CreatedAt, &i.Title, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByUserAndDate = `-- name: ListMemoriesByUserAndDate :many
SELECT id, record_time, title, content, created_at
FROM memories
WHERE user_id = $1
  AND record_date = $2::date
ORDER BY record_time ASC
LIMIT 500
`

type ListMemoriesByUserAndDateParams struct {
	UserID  string      `json:"userId"`
	Column2 pgtype.Date `json:"column2"`
}

type ListMemoriesByUserAndDateRow struct {
	ID         string             `json:"id"`
	RecordTime pgtype.Timestamptz `json:"recordTime"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) ListMemoriesByUserAndDate(ctx context.Context, arg ListMemoriesByUserAndDateParams) ([]ListMemoriesByUserAndDateRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesByUserAndDate, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoriesByUserAndDateRow{}
	for rows.Next() {
		var i ListMemoriesByUserAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordTime,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories SET title = $1, content = $2, record_time = $3, record_date = $6
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, record_time, record_date, title, content, created_at
`

type UpdateMemoryParams struct {
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	RecordTime pgtype.Timestamptz `json:"recordTime"`
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	RecordDate pgtype.Date        `json:"recordDate"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.Title,
		arg.Content,
		arg.RecordTime,
		arg.ID,
		arg.UserID,
		arg.RecordDate,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordTime,
		&i.RecordDate,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
