// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchCreateDiaryEntryImages(ctx context.Context, arg BatchCreateDiaryEntryImagesParams) error
	BatchDeleteFiles(ctx context.Context, dollar_1 []string) ([]BatchDeleteFilesRow, error)
	BatchMigrateUsersDailyCoversToPersonal(ctx context.Context, arg BatchMigrateUsersDailyCoversToPersonalParams) error
	BatchUpdateUsersCurrentFamilyToPersonal(ctx context.Context, arg BatchUpdateUsersCurrentFamilyToPersonalParams) error
	BatchUpsertFamilyMembership(ctx context.Context, arg BatchUpsertFamilyMembershipParams) error
	BatchUpsertFamilyMembershipOwner(ctx context.Context, arg BatchUpsertFamilyMembershipOwnerParams) error
	ClearAvatarReferencesToOrphanFiles(ctx context.Context) error
	ClearFamilyDailyImageCoverByFileID(ctx context.Context, arg ClearFamilyDailyImageCoverByFileIDParams) error
	ClearFamilyDailyImageCoverByFileIDs(ctx context.Context, arg ClearFamilyDailyImageCoverByFileIDsParams) error
	ClearFamilyDailyManualCover(ctx context.Context, arg ClearFamilyDailyManualCoverParams) error
	ClearFamilyDailyManualCoverByFileID(ctx context.Context, arg ClearFamilyDailyManualCoverByFileIDParams) error
	ClearFamilyDailyManualCoverByFileIDs(ctx context.Context, arg ClearFamilyDailyManualCoverByFileIDsParams) error
	ClearTrajectoryFamilyID(ctx context.Context, familyID string) error
	ClearUserAvatarByFile(ctx context.Context, arg ClearUserAvatarByFileParams) error
	CloseOrder(ctx context.Context, arg CloseOrderParams) (int64, error)
	CloseOrdersBatch(ctx context.Context, arg CloseOrdersBatchParams) (int64, error)
	ClosePendingOrdersByUser(ctx context.Context, userID pgtype.Text) error
	ClosePendingOrdersByUserAndVIP(ctx context.Context, arg ClosePendingOrdersByUserAndVIPParams) error
	CountDiaryEntries(ctx context.Context, arg CountDiaryEntriesParams) (int64, error)
	CountDiaryEntriesByDiaryID(ctx context.Context, diaryID string) (int64, error)
	CountDiaryEntriesByUsers(ctx context.Context, dollar_1 []string) (int64, error)
	CountFamilyDailyCovers(ctx context.Context, familyID string) (int64, error)
	CountFamilyMembers(ctx context.Context, familyID string) (int64, error)
	CountInviterMonthlyRewardDays(ctx context.Context, arg CountInviterMonthlyRewardDaysParams) (int32, error)
	CountMemoriesByUserAndDate(ctx context.Context, arg CountMemoriesByUserAndDateParams) (int64, error)
	CountSysConfig(ctx context.Context) (int64, error)
	CountWeeklyDiaryEntriesByUsers(ctx context.Context, arg CountWeeklyDiaryEntriesByUsersParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAutoRecordEntry(ctx context.Context, arg CreateAutoRecordEntryParams) error
	CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (DiaryEntry, error)
	CreateDiaryEntryImage(ctx context.Context, arg CreateDiaryEntryImageParams) error
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (string, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error)
	CreateUserInviteCode(ctx context.Context, arg CreateUserInviteCodeParams) (UserInviteCode, error)
	DecrementAIDailyQuotaUsed(ctx context.Context, arg DecrementAIDailyQuotaUsedParams) (int32, error)
	DeleteAIDailyQuotaUsageByUserID(ctx context.Context, userID string) error
	DeleteAPIKeyByUser(ctx context.Context, userID string) error
	// 在事务内先锁定日记行、再删除图片关联并返回 file_id，最后删除日记（级联删除条目）。
	// FOR UPDATE 阻止并发创建条目，确保返回的 file_id 与实际被级联删除的图片完全一致。
	DeleteDiaryAndEntriesReturningFileIDs(ctx context.Context, id string) ([]string, error)
	DeleteDiaryEntryImages(ctx context.Context, diaryEntryID string) error
	// 在事务内锁定条目行、删除图片关联并返回 file_id，最后删除日记条目。
	// FOR UPDATE 阻止并发更新条目，确保返回的 file_id 与实际被级联删除的图片完全一致。
	DeleteDiaryEntryReturningFileIDs(ctx context.Context, id string) ([]string, error)
	DeleteExcessDialogLogs(ctx context.Context, arg DeleteExcessDialogLogsParams) (int64, error)
	DeleteExpiredAPIKeys(ctx context.Context, dollar_1 int64) (int64, error)
	DeleteFamily(ctx context.Context, id string) error
	DeleteFamilyDailyCovers(ctx context.Context, familyID string) error
	DeleteFamilyMembers(ctx context.Context, familyID string) error
	DeleteFamilyMembership(ctx context.Context, arg DeleteFamilyMembershipParams) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMemoriesByUserAndDate(ctx context.Context, arg DeleteMemoriesByUserAndDateParams) (int64, error)
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error)
	DeleteOldDialogLogs(ctx context.Context, dollar_1 int64) (int64, error)
	DeleteStaleTrajectories(ctx context.Context, dollar_1 int64) (int64, error)
	DeleteTrajectories(ctx context.Context, dollar_1 []string) error
	DeleteTrajectoryCovers(ctx context.Context, arg DeleteTrajectoryCoversParams) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserCommonAddresses(ctx context.Context, userID string) error
	DeleteUserInviteCodeByUserID(ctx context.Context, userID string) error
	DeleteUserVIP(ctx context.Context, userID string) error
	FindTrajectoryCovers(ctx context.Context, arg FindTrajectoryCoversParams) ([]FindTrajectoryCoversRow, error)
	GetAIDailyQuotaUsed(ctx context.Context, arg GetAIDailyQuotaUsedParams) (int32, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetAPIKeyByUser(ctx context.Context, userID string) (GetAPIKeyByUserRow, error)
	GetDiaryByID(ctx context.Context, id string) (Diary, error)
	GetDiaryByUserAndDate(ctx context.Context, arg GetDiaryByUserAndDateParams) (Diary, error)
	GetDiaryEntriesByImageID(ctx context.Context, arg GetDiaryEntriesByImageIDParams) ([]int32, error)
	GetDiaryEntry(ctx context.Context, id string) (DiaryEntry, error)
	GetDiaryFirstRecordDate(ctx context.Context, dollar_1 []string) (pgtype.Date, error)
	GetFamilyByID(ctx context.Context, id string) (Family, error)
	GetFamilyDailyCover(ctx context.Context, arg GetFamilyDailyCoverParams) (GetFamilyDailyCoverRow, error)
	GetFamilyOwner(ctx context.Context, familyID string) (string, error)
	GetFileByID(ctx context.Context, id string) (File, error)
	GetFileByIDForUpdate(ctx context.Context, id string) (File, error)
	GetFileByPath(ctx context.Context, path string) (File, error)
	GetFileReferences(ctx context.Context, coverFileID pgtype.Text) (GetFileReferencesRow, error)
	GetFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error)
	GetLatestCoordinateByAddress(ctx context.Context, arg GetLatestCoordinateByAddressParams) (GetLatestCoordinateByAddressRow, error)
	// 选择当日最新图片日记作为 image 优先级封面。
	// 排序语义：用户手动排序（sort_order 越小越靠前） > 日记记录时间 > 图片上传时间。
	GetLatestImageEntry(ctx context.Context, arg GetLatestImageEntryParams) (GetLatestImageEntryRow, error)
	GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error)
	GetOrderByOutTradeNo(ctx context.Context, outTradeNo string) (Order, error)
	GetSysConfig(ctx context.Context) (SysConfig, error)
	GetUserAvatarMarker(ctx context.Context, userID string) (GetUserAvatarMarkerRow, error)
	GetUserAvatarMarkersByIDs(ctx context.Context, dollar_1 []string) ([]GetUserAvatarMarkersByIDsRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByIDForUpdate(ctx context.Context, id string) (GetUserByIDForUpdateRow, error)
	GetUserByOpenID(ctx context.Context, openID string) (GetUserByOpenIDRow, error)
	GetUserByUnionID(ctx context.Context, unionid pgtype.Text) (GetUserByUnionIDRow, error)
	GetUserCommonAddress(ctx context.Context, arg GetUserCommonAddressParams) (GetUserCommonAddressRow, error)
	GetUserInviteByUserID(ctx context.Context, userID string) (UserInvite, error)
	GetUserInviteCode(ctx context.Context, userID string) (string, error)
	GetUserLastAutoEntry(ctx context.Context, createdBy string) (GetUserLastAutoEntryRow, error)
	GetUserLastAutoEntryByDate(ctx context.Context, arg GetUserLastAutoEntryByDateParams) (GetUserLastAutoEntryByDateRow, error)
	GetUserSessionKeyByID(ctx context.Context, id string) (pgtype.Text, error)
	GetUserVIP(ctx context.Context, userID string) (UserVip, error)
	GetUserVIPForUpdate(ctx context.Context, userID string) (UserVip, error)
	GetVIPByID(ctx context.Context, id string) (Vip, error)
	GetWxMPAccountByOpenID(ctx context.Context, mpOpenid string) (WxMpAccount, error)
	GetWxMPAccountByUnionID(ctx context.Context, unionid pgtype.Text) (WxMpAccount, error)
	GetWxMPAccountByUserID(ctx context.Context, userID pgtype.Text) (WxMpAccount, error)
	HasVIPClaim(ctx context.Context, arg HasVIPClaimParams) (bool, error)
	IncrementAIDailyQuotaUsed(ctx context.Context, arg IncrementAIDailyQuotaUsedParams) (IncrementAIDailyQuotaUsedRow, error)
	IncrementTrajectoryGeocodeAttempts(ctx context.Context, dollar_1 []string) error
	InsertAIDialogLog(ctx context.Context, arg InsertAIDialogLogParams) error
	InsertTrajectories(ctx context.Context, arg InsertTrajectoriesParams) error
	InsertUserCommonAddresses(ctx context.Context, arg InsertUserCommonAddressesParams) error
	IsFamilyMember(ctx context.Context, arg IsFamilyMemberParams) (bool, error)
	IsImageUsedByFamilyDate(ctx context.Context, arg IsImageUsedByFamilyDateParams) (bool, error)
	LinkWxMPAccountByUnionID(ctx context.Context, arg LinkWxMPAccountByUnionIDParams) error
	ListAIBackgroundEntries(ctx context.Context, arg ListAIBackgroundEntriesParams) ([]ListAIBackgroundEntriesRow, error)
	ListAbnormalAlertCandidates(ctx context.Context, arg ListAbnormalAlertCandidatesParams) ([]ListAbnormalAlertCandidatesRow, error)
	ListActiveFreeVIPs(ctx context.Context) ([]Vip, error)
	ListActivePaidVIPs(ctx context.Context) ([]Vip, error)
	ListAddressEntriesByDates(ctx context.Context, arg ListAddressEntriesByDatesParams) ([]ListAddressEntriesByDatesRow, error)
	ListDiaryCards(ctx context.Context, arg ListDiaryCardsParams) ([]ListDiaryCardsRow, error)
	ListDiaryCardsByDates(ctx context.Context, arg ListDiaryCardsByDatesParams) ([]ListDiaryCardsByDatesRow, error)
	ListDiaryEntries(ctx context.Context, arg ListDiaryEntriesParams) ([]ListDiaryEntriesRow, error)
	ListDiaryEntriesByDateRange(ctx context.Context, arg ListDiaryEntriesByDateRangeParams) ([]ListDiaryEntriesByDateRangeRow, error)
	ListDiaryEntryImageFileIDsByDiaryID(ctx context.Context, diaryID string) ([]string, error)
	ListDiaryEntryImagePaths(ctx context.Context, diaryEntryID string) ([]ListDiaryEntryImagePathsRow, error)
	ListDiaryEntryImagePathsByEntryIDs(ctx context.Context, dollar_1 []string) ([]ListDiaryEntryImagePathsByEntryIDsRow, error)
	ListDiaryEntryImages(ctx context.Context, diaryEntryID string) ([]string, error)
	ListFamilyDailyCovers(ctx context.Context, arg ListFamilyDailyCoversParams) ([]ListFamilyDailyCoversRow, error)
	ListFamilyMemberPersonalFamilies(ctx context.Context, familyID string) ([]ListFamilyMemberPersonalFamiliesRow, error)
	ListFamilyMembers(ctx context.Context, familyID string) ([]ListFamilyMembersRow, error)
	ListFilesByCreator(ctx context.Context, arg ListFilesByCreatorParams) ([]ListFilesByCreatorRow, error)
	ListLocationEntries(ctx context.Context, arg ListLocationEntriesParams) ([]ListLocationEntriesRow, error)
	ListMemoriesByDateRange(ctx context.Context, arg ListMemoriesByDateRangeParams) ([]ListMemoriesByDateRangeRow, error)
	ListMemoriesByUserAndDate(ctx context.Context, arg ListMemoriesByUserAndDateParams) ([]ListMemoriesByUserAndDateRow, error)
	ListOrphanFilesByCreator(ctx context.Context, arg ListOrphanFilesByCreatorParams) ([]ListOrphanFilesByCreatorRow, error)
	ListPendingAutoRecordUsers(ctx context.Context, limit int32) ([]string, error)
	ListPendingOrdersBefore(ctx context.Context, arg ListPendingOrdersBeforeParams) ([]Order, error)
	ListRecentDialogLogs(ctx context.Context, arg ListRecentDialogLogsParams) ([]AiDialogLog, error)
	ListTopAddressesByUser(ctx context.Context, arg ListTopAddressesByUserParams) ([]ListTopAddressesByUserRow, error)
	ListTrajectoriesByUser(ctx context.Context, arg ListTrajectoriesByUserParams) ([]AutoRecordTrajectory, error)
	ListUserCommonAddresses(ctx context.Context, userID string) ([]ListUserCommonAddressesRow, error)
	ListUserInviteQRCodeFiles(ctx context.Context, arg ListUserInviteQRCodeFilesParams) ([]ListUserInviteQRCodeFilesRow, error)
	ListUserInvitesByInviter(ctx context.Context, inviterID string) ([]ListUserInvitesByInviterRow, error)
	ListUserMcpEntries(ctx context.Context, arg ListUserMcpEntriesParams) ([]ListUserMcpEntriesRow, error)
	ListUsersWithDiaryChangesSince(ctx context.Context, arg ListUsersWithDiaryChangesSinceParams) ([]string, error)
	ListUsersWithExcessDialogLogs(ctx context.Context, arg ListUsersWithExcessDialogLogsParams) ([]string, error)
	LockInviterReward(ctx context.Context, dollar_1 pgtype.Text) error
	MarkAbnormalAlertSent(ctx context.Context, id string) (int64, error)
	MarkInviteeRewarded(ctx context.Context, id string) (int64, error)
	MarkInviterRewarded(ctx context.Context, id string) (int64, error)
	MergeUserCommonAddress(ctx context.Context, arg MergeUserCommonAddressParams) error
	MigrateFamilyDailyCovers(ctx context.Context, arg MigrateFamilyDailyCoversParams) error
	MigrateUserDailyCoversToFamily(ctx context.Context, arg MigrateUserDailyCoversToFamilyParams) error
	NeedsCommonAddressRefresh(ctx context.Context, userID string) (pgtype.Bool, error)
	NullifyOrdersByUser(ctx context.Context, userID pgtype.Text) error
	RenameUserCommonAddress(ctx context.Context, arg RenameUserCommonAddressParams) error
	ResolveInviterFromCode(ctx context.Context, shortCode string) (string, error)
	ScanOldSystemFiles(ctx context.Context, id string) ([]ScanOldSystemFilesRow, error)
	ScanOrphanFiles(ctx context.Context, id string) ([]ScanOrphanFilesRow, error)
	SetFamilyDailyManualCover(ctx context.Context, arg SetFamilyDailyManualCoverParams) error
	TouchDiaryUpdatedAt(ctx context.Context, id string) error
	TouchWxMPAccountInteractTime(ctx context.Context, mpOpenid string) error
	UpdateDiaryEntriesAddress(ctx context.Context, arg UpdateDiaryEntriesAddressParams) (int64, error)
	UpdateDiaryEntriesAddressBatch(ctx context.Context, arg UpdateDiaryEntriesAddressBatchParams) (int64, error)
	UpdateDiaryEntry(ctx context.Context, arg UpdateDiaryEntryParams) (int64, error)
	UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error)
	UpdateOrderPaid(ctx context.Context, arg UpdateOrderPaidParams) (int64, error)
	UpdateUserAlertSubscribe(ctx context.Context, arg UpdateUserAlertSubscribeParams) error
	UpdateUserAutoRecord(ctx context.Context, arg UpdateUserAutoRecordParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserCurrentFamily(ctx context.Context, arg UpdateUserCurrentFamilyParams) error
	UpdateUserLang(ctx context.Context, arg UpdateUserLangParams) error
	UpdateUserLastActiveAt(ctx context.Context, id string) error
	UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) error
	UpdateUserPersonalFamily(ctx context.Context, arg UpdateUserPersonalFamilyParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdateUserSessionKey(ctx context.Context, arg UpdateUserSessionKeyParams) error
	UpdateUserUnionID(ctx context.Context, arg UpdateUserUnionIDParams) error
	UpdateUsersCurrentFamily(ctx context.Context, arg UpdateUsersCurrentFamilyParams) error
	UpdateWxMPAccountSubscribeStatus(ctx context.Context, arg UpdateWxMPAccountSubscribeStatusParams) error
	UpsertDiary(ctx context.Context, arg UpsertDiaryParams) (string, error)
	UpsertFamilyDailyCover(ctx context.Context, arg UpsertFamilyDailyCoverParams) error
	UpsertFamilyMembership(ctx context.Context, arg UpsertFamilyMembershipParams) (string, error)
	UpsertUserAvatarMarker(ctx context.Context, arg UpsertUserAvatarMarkerParams) error
	UpsertUserVIP(ctx context.Context, arg UpsertUserVIPParams) (UserVip, error)
	UpsertVIPClaim(ctx context.Context, arg UpsertVIPClaimParams) (int64, error)
	UpsertWxMPAccount(ctx context.Context, arg UpsertWxMPAccountParams) (WxMpAccount, error)
}

var _ Querier = (*Queries)(nil)
