// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sys_config.sql

package sqlc

import (
	"context"
)

const countSysConfig = `-- name: CountSysConfig :one
SELECT COUNT(*) FROM sys_configs
`

func (q *Queries) CountSysConfig(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSysConfig)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSysConfig = `-- name: GetSysConfig :one
SELECT id, ai_config, sys_config, default_diary_config, ai_prompt, updated_at FROM sys_configs WHERE id = 'default'
`

func (q *Queries) GetSysConfig(ctx context.Context) (SysConfig, error) {
	row := q.db.QueryRow(ctx, getSysConfig)
	var i SysConfig
	err := row.Scan(
		&i.ID,
		&i.AiConfig,
		&i.SysConfig,
		&i.DefaultDiaryConfig,
		&i.AiPrompt,
		&i.UpdatedAt,
	)
	return i, err
}
