// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateUsersCurrentFamilyToPersonal = `-- name: BatchUpdateUsersCurrentFamilyToPersonal :exec
UPDATE users u SET current_family_id = p.personal_family_id, updated_at = now()
FROM (
    SELECT unnest($1::text[]) AS user_id, unnest($2::text[]) AS personal_family_id
) AS p
WHERE u.id = p.user_id
`

type BatchUpdateUsersCurrentFamilyToPersonalParams struct {
	UserIds           []string `json:"userIds"`
	PersonalFamilyIds []string `json:"personalFamilyIds"`
}

func (q *Queries) BatchUpdateUsersCurrentFamilyToPersonal(ctx context.Context, arg BatchUpdateUsersCurrentFamilyToPersonalParams) error {
	_, err := q.db.Exec(ctx, batchUpdateUsersCurrentFamilyToPersonal, arg.UserIds, arg.PersonalFamilyIds)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, open_id, unionid, phone_number, avatar, avatar_file_id, nickname,
    user_type, phone_bind_time, auto_record_enabled, session_key,
    personal_family_id, current_family_id, invited_by, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, now(), now())
RETURNING id, open_id, unionid, phone_number, avatar, avatar_file_id, nickname, user_type, phone_bind_time, auto_record_enabled, personal_family_id, current_family_id, created_at, updated_at, session_key, invited_by, abnormal_subscribe_accepted, abnormal_alert_sent_at, last_active_at, lang
`

type CreateUserParams struct {
	ID                string             `json:"id"`
	OpenID            string             `json:"openId"`
	Unionid           pgtype.Text        `json:"unionid"`
	PhoneNumber       pgtype.Text        `json:"phoneNumber"`
	Avatar            pgtype.Text        `json:"avatar"`
	AvatarFileID      pgtype.Text        `json:"avatarFileId"`
	Nickname          pgtype.Text        `json:"nickname"`
	UserType          string             `json:"userType"`
	PhoneBindTime     pgtype.Timestamptz `json:"phoneBindTime"`
	AutoRecordEnabled bool               `json:"autoRecordEnabled"`
	SessionKey        pgtype.Text        `json:"sessionKey"`
	PersonalFamilyID  pgtype.Text        `json:"personalFamilyId"`
	CurrentFamilyID   pgtype.Text        `json:"currentFamilyId"`
	InvitedBy         pgtype.Text        `json:"invitedBy"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.OpenID,
		arg.Unionid,
		arg.PhoneNumber,
		arg.Avatar,
		arg.AvatarFileID,
		arg.Nickname,
		arg.UserType,
		arg.PhoneBindTime,
		arg.AutoRecordEnabled,
		arg.SessionKey,
		arg.PersonalFamilyID,
		arg.CurrentFamilyID,
		arg.InvitedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.Unionid,
		&i.PhoneNumber,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Nickname,
		&i.UserType,
		&i.PhoneBindTime,
		&i.AutoRecordEnabled,
		&i.PersonalFamilyID,
		&i.CurrentFamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionKey,
		&i.InvitedBy,
		&i.AbnormalSubscribeAccepted,
		&i.AbnormalAlertSentAt,
		&i.LastActiveAt,
		&i.Lang,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserAvatarMarker = `-- name: GetUserAvatarMarker :one
SELECT marker_path, storage_type FROM user_avatar_markers WHERE user_id = $1
`

type GetUserAvatarMarkerRow struct {
	MarkerPath  string `json:"markerPath"`
	StorageType string `json:"storageType"`
}

func (q *Queries) GetUserAvatarMarker(ctx context.Context, userID string) (GetUserAvatarMarkerRow, error) {
	row := q.db.QueryRow(ctx, getUserAvatarMarker, userID)
	var i GetUserAvatarMarkerRow
	err := row.Scan(&i.MarkerPath, &i.StorageType)
	return i, err
}

const getUserAvatarMarkersByIDs = `-- name: GetUserAvatarMarkersByIDs :many
SELECT user_id, marker_path, storage_type FROM user_avatar_markers WHERE user_id = ANY($1::text[])
`

type GetUserAvatarMarkersByIDsRow struct {
	UserID      string `json:"userId"`
	MarkerPath  string `json:"markerPath"`
	StorageType string `json:"storageType"`
}

func (q *Queries) GetUserAvatarMarkersByIDs(ctx context.Context, dollar_1 []string) ([]GetUserAvatarMarkersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserAvatarMarkersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAvatarMarkersByIDsRow{}
	for rows.Next() {
		var i GetUserAvatarMarkersByIDsRow
		if err := rows.Scan(&i.UserID, &i.MarkerPath, &i.StorageType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, open_id, unionid, phone_number, avatar, avatar_file_id, nickname, user_type, phone_bind_time, auto_record_enabled, personal_family_id, current_family_id, invited_by, lang, created_at, updated_at, abnormal_subscribe_accepted, last_active_at FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID                        string             `json:"id"`
	OpenID                    string             `json:"openId"`
	Unionid                   pgtype.Text        `json:"unionid"`
	PhoneNumber               pgtype.Text        `json:"phoneNumber"`
	Avatar                    pgtype.Text        `json:"avatar"`
	AvatarFileID              pgtype.Text        `json:"avatarFileId"`
	Nickname                  pgtype.Text        `json:"nickname"`
	UserType                  string             `json:"userType"`
	PhoneBindTime             pgtype.Timestamptz `json:"phoneBindTime"`
	AutoRecordEnabled         bool               `json:"autoRecordEnabled"`
	PersonalFamilyID          pgtype.Text        `json:"personalFamilyId"`
	CurrentFamilyID           pgtype.Text        `json:"currentFamilyId"`
	InvitedBy                 pgtype.Text        `json:"invitedBy"`
	Lang                      string             `json:"lang"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	AbnormalSubscribeAccepted bool               `json:"abnormalSubscribeAccepted"`
	LastActiveAt              pgtype.Timestamptz `json:"lastActiveAt"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.Unionid,
		&i.PhoneNumber,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Nickname,
		&i.UserType,
		&i.PhoneBindTime,
		&i.AutoRecordEnabled,
		&i.PersonalFamilyID,
		&i.CurrentFamilyID,
		&i.InvitedBy,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AbnormalSubscribeAccepted,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, open_id, unionid, phone_number, avatar, avatar_file_id, nickname, user_type, phone_bind_time, auto_record_enabled, personal_family_id, current_family_id, invited_by, lang, created_at, updated_at, abnormal_subscribe_accepted, last_active_at FROM users WHERE id = $1 FOR UPDATE
`

type GetUserByIDForUpdateRow struct {
	ID                        string             `json:"id"`
	OpenID                    string             `json:"openId"`
	Unionid                   pgtype.Text        `json:"unionid"`
	PhoneNumber               pgtype.Text        `json:"phoneNumber"`
	Avatar                    pgtype.Text        `json:"avatar"`
	AvatarFileID              pgtype.Text        `json:"avatarFileId"`
	Nickname                  pgtype.Text        `json:"nickname"`
	UserType                  string             `json:"userType"`
	PhoneBindTime             pgtype.Timestamptz `json:"phoneBindTime"`
	AutoRecordEnabled         bool               `json:"autoRecordEnabled"`
	PersonalFamilyID          pgtype.Text        `json:"personalFamilyId"`
	CurrentFamilyID           pgtype.Text        `json:"currentFamilyId"`
	InvitedBy                 pgtype.Text        `json:"invitedBy"`
	Lang                      string             `json:"lang"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	AbnormalSubscribeAccepted bool               `json:"abnormalSubscribeAccepted"`
	LastActiveAt              pgtype.Timestamptz `json:"lastActiveAt"`
}

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id string) (GetUserByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForUpdate, id)
	var i GetUserByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.Unionid,
		&i.PhoneNumber,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Nickname,
		&i.UserType,
		&i.PhoneBindTime,
		&i.AutoRecordEnabled,
		&i.PersonalFamilyID,
		&i.CurrentFamilyID,
		&i.InvitedBy,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AbnormalSubscribeAccepted,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByOpenID = `-- name: GetUserByOpenID :one
SELECT id, open_id, unionid, phone_number, avatar, avatar_file_id, nickname, user_type, phone_bind_time, auto_record_enabled, personal_family_id, current_family_id, invited_by, lang, created_at, updated_at, abnormal_subscribe_accepted, last_active_at FROM users WHERE open_id = $1
`

type GetUserByOpenIDRow struct {
	ID                        string             `json:"id"`
	OpenID                    string             `json:"openId"`
	Unionid                   pgtype.Text        `json:"unionid"`
	PhoneNumber               pgtype.Text        `json:"phoneNumber"`
	Avatar                    pgtype.Text        `json:"avatar"`
	AvatarFileID              pgtype.Text        `json:"avatarFileId"`
	Nickname                  pgtype.Text        `json:"nickname"`
	UserType                  string             `json:"userType"`
	PhoneBindTime             pgtype.Timestamptz `json:"phoneBindTime"`
	AutoRecordEnabled         bool               `json:"autoRecordEnabled"`
	PersonalFamilyID          pgtype.Text        `json:"personalFamilyId"`
	CurrentFamilyID           pgtype.Text        `json:"currentFamilyId"`
	InvitedBy                 pgtype.Text        `json:"invitedBy"`
	Lang                      string             `json:"lang"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	AbnormalSubscribeAccepted bool               `json:"abnormalSubscribeAccepted"`
	LastActiveAt              pgtype.Timestamptz `json:"lastActiveAt"`
}

func (q *Queries) GetUserByOpenID(ctx context.Context, openID string) (GetUserByOpenIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByOpenID, openID)
	var i GetUserByOpenIDRow
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.Unionid,
		&i.PhoneNumber,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Nickname,
		&i.UserType,
		&i.PhoneBindTime,
		&i.AutoRecordEnabled,
		&i.PersonalFamilyID,
		&i.CurrentFamilyID,
		&i.InvitedBy,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AbnormalSubscribeAccepted,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByUnionID = `-- name: GetUserByUnionID :one
SELECT id, open_id, unionid, phone_number, avatar, avatar_file_id, nickname, user_type, phone_bind_time, auto_record_enabled, personal_family_id, current_family_id, invited_by, lang, created_at, updated_at, abnormal_subscribe_accepted, last_active_at FROM users WHERE unionid = $1
`

type GetUserByUnionIDRow struct {
	ID                        string             `json:"id"`
	OpenID                    string             `json:"openId"`
	Unionid                   pgtype.Text        `json:"unionid"`
	PhoneNumber               pgtype.Text        `json:"phoneNumber"`
	Avatar                    pgtype.Text        `json:"avatar"`
	AvatarFileID              pgtype.Text        `json:"avatarFileId"`
	Nickname                  pgtype.Text        `json:"nickname"`
	UserType                  string             `json:"userType"`
	PhoneBindTime             pgtype.Timestamptz `json:"phoneBindTime"`
	AutoRecordEnabled         bool               `json:"autoRecordEnabled"`
	PersonalFamilyID          pgtype.Text        `json:"personalFamilyId"`
	CurrentFamilyID           pgtype.Text        `json:"currentFamilyId"`
	InvitedBy                 pgtype.Text        `json:"invitedBy"`
	Lang                      string             `json:"lang"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	AbnormalSubscribeAccepted bool               `json:"abnormalSubscribeAccepted"`
	LastActiveAt              pgtype.Timestamptz `json:"lastActiveAt"`
}

func (q *Queries) GetUserByUnionID(ctx context.Context, unionid pgtype.Text) (GetUserByUnionIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByUnionID, unionid)
	var i GetUserByUnionIDRow
	err := row.Scan(
		&i.ID,
		&i.OpenID,
		&i.Unionid,
		&i.PhoneNumber,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Nickname,
		&i.UserType,
		&i.PhoneBindTime,
		&i.AutoRecordEnabled,
		&i.PersonalFamilyID,
		&i.CurrentFamilyID,
		&i.InvitedBy,
		&i.Lang,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AbnormalSubscribeAccepted,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserSessionKeyByID = `-- name: GetUserSessionKeyByID :one
SELECT session_key FROM users WHERE id = $1
`

func (q *Queries) GetUserSessionKeyByID(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserSessionKeyByID, id)
	var session_key pgtype.Text
	err := row.Scan(&session_key)
	return session_key, err
}

const markAbnormalAlertSent = `-- name: MarkAbnormalAlertSent :execrows
UPDATE users
SET abnormal_alert_sent_at = now(),
    updated_at = now()
WHERE id = $1
  AND (
      abnormal_alert_sent_at IS NULL
      OR (abnormal_alert_sent_at AT TIME ZONE 'Asia/Shanghai')::date < (now() AT TIME ZONE 'Asia/Shanghai')::date
  )
`

func (q *Queries) MarkAbnormalAlertSent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markAbnormalAlertSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserAlertSubscribe = `-- name: UpdateUserAlertSubscribe :exec
UPDATE users SET
    abnormal_subscribe_accepted = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserAlertSubscribeParams struct {
	ID                        string `json:"id"`
	AbnormalSubscribeAccepted bool   `json:"abnormalSubscribeAccepted"`
}

func (q *Queries) UpdateUserAlertSubscribe(ctx context.Context, arg UpdateUserAlertSubscribeParams) error {
	_, err := q.db.Exec(ctx, updateUserAlertSubscribe, arg.ID, arg.AbnormalSubscribeAccepted)
	return err
}

const updateUserAutoRecord = `-- name: UpdateUserAutoRecord :exec
UPDATE users SET auto_record_enabled = $2, updated_at = now() WHERE id = $1
`

type UpdateUserAutoRecordParams struct {
	ID                string `json:"id"`
	AutoRecordEnabled bool   `json:"autoRecordEnabled"`
}

func (q *Queries) UpdateUserAutoRecord(ctx context.Context, arg UpdateUserAutoRecordParams) error {
	_, err := q.db.Exec(ctx, updateUserAutoRecord, arg.ID, arg.AutoRecordEnabled)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar = $2, avatar_file_id = $3, updated_at = now() WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID           string      `json:"id"`
	Avatar       pgtype.Text `json:"avatar"`
	AvatarFileID pgtype.Text `json:"avatarFileId"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.Avatar, arg.AvatarFileID)
	return err
}

const updateUserCurrentFamily = `-- name: UpdateUserCurrentFamily :exec
UPDATE users SET current_family_id = $2, updated_at = now() WHERE id = $1
`

type UpdateUserCurrentFamilyParams struct {
	ID              string      `json:"id"`
	CurrentFamilyID pgtype.Text `json:"currentFamilyId"`
}

func (q *Queries) UpdateUserCurrentFamily(ctx context.Context, arg UpdateUserCurrentFamilyParams) error {
	_, err := q.db.Exec(ctx, updateUserCurrentFamily, arg.ID, arg.CurrentFamilyID)
	return err
}

const updateUserLang = `-- name: UpdateUserLang :exec
UPDATE users SET lang = $2, updated_at = now() WHERE id = $1
`

type UpdateUserLangParams struct {
	ID   string `json:"id"`
	Lang string `json:"lang"`
}

func (q *Queries) UpdateUserLang(ctx context.Context, arg UpdateUserLangParams) error {
	_, err := q.db.Exec(ctx, updateUserLang, arg.ID, arg.Lang)
	return err
}

const updateUserLastActiveAt = `-- name: UpdateUserLastActiveAt :exec
UPDATE users SET last_active_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserLastActiveAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserLastActiveAt, id)
	return err
}

const updateUserNickname = `-- name: UpdateUserNickname :exec
UPDATE users SET nickname = $2, updated_at = now() WHERE id = $1
`

type UpdateUserNicknameParams struct {
	ID       string      `json:"id"`
	Nickname pgtype.Text `json:"nickname"`
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) error {
	_, err := q.db.Exec(ctx, updateUserNickname, arg.ID, arg.Nickname)
	return err
}

const updateUserPersonalFamily = `-- name: UpdateUserPersonalFamily :exec
UPDATE users SET personal_family_id = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPersonalFamilyParams struct {
	ID               string      `json:"id"`
	PersonalFamilyID pgtype.Text `json:"personalFamilyId"`
}

func (q *Queries) UpdateUserPersonalFamily(ctx context.Context, arg UpdateUserPersonalFamilyParams) error {
	_, err := q.db.Exec(ctx, updateUserPersonalFamily, arg.ID, arg.PersonalFamilyID)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE users SET phone_number = $2, phone_bind_time = $3, updated_at = now() WHERE id = $1
`

type UpdateUserPhoneParams struct {
	ID            string             `json:"id"`
	PhoneNumber   pgtype.Text        `json:"phoneNumber"`
	PhoneBindTime pgtype.Timestamptz `json:"phoneBindTime"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.Exec(ctx, updateUserPhone, arg.ID, arg.PhoneNumber, arg.PhoneBindTime)
	return err
}

const updateUserSessionKey = `-- name: UpdateUserSessionKey :exec
UPDATE users SET session_key = $2, updated_at = now() WHERE id = $1
`

type UpdateUserSessionKeyParams struct {
	ID         string      `json:"id"`
	SessionKey pgtype.Text `json:"sessionKey"`
}

func (q *Queries) UpdateUserSessionKey(ctx context.Context, arg UpdateUserSessionKeyParams) error {
	_, err := q.db.Exec(ctx, updateUserSessionKey, arg.ID, arg.SessionKey)
	return err
}

const updateUserUnionID = `-- name: UpdateUserUnionID :exec
UPDATE users SET unionid = $2, updated_at = now() WHERE id = $1
`

type UpdateUserUnionIDParams struct {
	ID      string      `json:"id"`
	Unionid pgtype.Text `json:"unionid"`
}

func (q *Queries) UpdateUserUnionID(ctx context.Context, arg UpdateUserUnionIDParams) error {
	_, err := q.db.Exec(ctx, updateUserUnionID, arg.ID, arg.Unionid)
	return err
}

const updateUsersCurrentFamily = `-- name: UpdateUsersCurrentFamily :exec
UPDATE users SET current_family_id = $2, updated_at = now() WHERE id = ANY($1::text[])
`

type UpdateUsersCurrentFamilyParams struct {
	Column1         []string    `json:"column1"`
	CurrentFamilyID pgtype.Text `json:"currentFamilyId"`
}

func (q *Queries) UpdateUsersCurrentFamily(ctx context.Context, arg UpdateUsersCurrentFamilyParams) error {
	_, err := q.db.Exec(ctx, updateUsersCurrentFamily, arg.Column1, arg.CurrentFamilyID)
	return err
}

const upsertUserAvatarMarker = `-- name: UpsertUserAvatarMarker :exec
INSERT INTO user_avatar_markers (user_id, marker_path, storage_type, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id)
DO UPDATE SET
    marker_path = EXCLUDED.marker_path,
    storage_type = EXCLUDED.storage_type,
    updated_at = now()
`

type UpsertUserAvatarMarkerParams struct {
	UserID      string `json:"userId"`
	MarkerPath  string `json:"markerPath"`
	StorageType string `json:"storageType"`
}

func (q *Queries) UpsertUserAvatarMarker(ctx context.Context, arg UpsertUserAvatarMarkerParams) error {
	_, err := q.db.Exec(ctx, upsertUserAvatarMarker, arg.UserID, arg.MarkerPath, arg.StorageType)
	return err
}
