// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vip.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUserVIPRow = `-- name: ClaimUserVIPRow :exec
INSERT INTO user_vips (id, user_id, begin_time, expire_time, created_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO NOTHING
`

type ClaimUserVIPRowParams struct {
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	BeginTime  pgtype.Timestamptz `json:"beginTime"`
	ExpireTime pgtype.Timestamptz `json:"expireTime"`
}

// 并发首次激活竞态防护：GetUserVIPForUpdate 对不存在的行无法加锁，两个并发首次激活
// 都走 ErrNoRows 创建路径会各自按 now 计算 expire、GREATEST 只保留较大者导致较小档时长丢失。
// 先 ON CONFLICT DO NOTHING 占位（expire=now），再 FOR UPDATE 重读串行化首次创建。
func (q *Queries) ClaimUserVIPRow(ctx context.Context, arg ClaimUserVIPRowParams) error {
	_, err := q.db.Exec(ctx, claimUserVIPRow,
		arg.ID,
		arg.UserID,
		arg.BeginTime,
		arg.ExpireTime,
	)
	return err
}

const deleteUserVIP = `-- name: DeleteUserVIP :exec
DELETE FROM user_vips WHERE user_id = $1
`

func (q *Queries) DeleteUserVIP(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserVIP, userID)
	return err
}

const getUserVIP = `-- name: GetUserVIP :one
SELECT id, user_id, begin_time, expire_time, created_at FROM user_vips WHERE user_id = $1
`

func (q *Queries) GetUserVIP(ctx context.Context, userID string) (UserVip, error) {
	row := q.db.QueryRow(ctx, getUserVIP, userID)
	var i UserVip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BeginTime,
		&i.ExpireTime,
		&i.CreatedAt,
	)
	return i, err
}

const getUserVIPForUpdate = `-- name: GetUserVIPForUpdate :one
SELECT id, user_id, begin_time, expire_time, created_at FROM user_vips WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetUserVIPForUpdate(ctx context.Context, userID string) (UserVip, error) {
	row := q.db.QueryRow(ctx, getUserVIPForUpdate, userID)
	var i UserVip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BeginTime,
		&i.ExpireTime,
		&i.CreatedAt,
	)
	return i, err
}

const getVIPByID = `-- name: GetVIPByID :one
SELECT id, type, name, time_limit_mark, time_limit_number, product_id, sort, is_active, prices, created_at FROM vips WHERE id = $1
`

func (q *Queries) GetVIPByID(ctx context.Context, id string) (Vip, error) {
	row := q.db.QueryRow(ctx, getVIPByID, id)
	var i Vip
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.TimeLimitMark,
		&i.TimeLimitNumber,
		&i.ProductID,
		&i.Sort,
		&i.IsActive,
		&i.Prices,
		&i.CreatedAt,
	)
	return i, err
}

const hasVIPClaim = `-- name: HasVIPClaim :one
SELECT EXISTS(SELECT 1 FROM user_vip_claims WHERE user_id = $1 AND vip_id = $2) AS exists
`

type HasVIPClaimParams struct {
	UserID string `json:"userId"`
	VipID  string `json:"vipId"`
}

func (q *Queries) HasVIPClaim(ctx context.Context, arg HasVIPClaimParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasVIPClaim, arg.UserID, arg.VipID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveFreeVIPs = `-- name: ListActiveFreeVIPs :many
SELECT id, type, name, time_limit_mark, time_limit_number, product_id, sort, is_active, prices, created_at FROM vips
WHERE is_active = true AND type = 'free'
ORDER BY sort ASC
LIMIT 100
`

func (q *Queries) ListActiveFreeVIPs(ctx context.Context) ([]Vip, error) {
	rows, err := q.db.Query(ctx, listActiveFreeVIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vip{}
	for rows.Next() {
		var i Vip
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.TimeLimitMark,
			&i.TimeLimitNumber,
			&i.ProductID,
			&i.Sort,
			&i.IsActive,
			&i.Prices,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePaidVIPs = `-- name: ListActivePaidVIPs :many
SELECT id, type, name, time_limit_mark, time_limit_number, product_id, sort, is_active, prices, created_at FROM vips
WHERE is_active = true AND type IN ('month', 'year')
ORDER BY sort ASC
LIMIT 100
`

func (q *Queries) ListActivePaidVIPs(ctx context.Context) ([]Vip, error) {
	rows, err := q.db.Query(ctx, listActivePaidVIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vip{}
	for rows.Next() {
		var i Vip
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.TimeLimitMark,
			&i.TimeLimitNumber,
			&i.ProductID,
			&i.Sort,
			&i.IsActive,
			&i.Prices,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserVIP = `-- name: UpsertUserVIP :one
INSERT INTO user_vips (id, user_id, begin_time, expire_time, created_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE SET
    begin_time = EXCLUDED.begin_time,
    -- GREATEST 防止并发/重复下发时缩短已购 VIP 时长（B2-11）
    expire_time = GREATEST(user_vips.expire_time, EXCLUDED.expire_time)
RETURNING id, user_id, begin_time, expire_time, created_at
`

type UpsertUserVIPParams struct {
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	BeginTime  pgtype.Timestamptz `json:"beginTime"`
	ExpireTime pgtype.Timestamptz `json:"expireTime"`
}

func (q *Queries) UpsertUserVIP(ctx context.Context, arg UpsertUserVIPParams) (UserVip, error) {
	row := q.db.QueryRow(ctx, upsertUserVIP,
		arg.ID,
		arg.UserID,
		arg.BeginTime,
		arg.ExpireTime,
	)
	var i UserVip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BeginTime,
		&i.ExpireTime,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVIPClaim = `-- name: UpsertVIPClaim :execrows
INSERT INTO user_vip_claims (id, user_id, vip_id, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id, vip_id) DO NOTHING
`

type UpsertVIPClaimParams struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	VipID  string `json:"vipId"`
}

func (q *Queries) UpsertVIPClaim(ctx context.Context, arg UpsertVIPClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertVIPClaim, arg.ID, arg.UserID, arg.VipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
