// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wx_mp_account.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWxMPAccountByOpenID = `-- name: GetWxMPAccountByOpenID :one
SELECT id, user_id, mp_openid, unionid, nickname, avatar, subscribed, subscribe_time, last_interact_time, created_at, updated_at
FROM wx_mp_accounts
WHERE mp_openid = $1
`

func (q *Queries) GetWxMPAccountByOpenID(ctx context.Context, mpOpenid string) (WxMpAccount, error) {
	row := q.db.QueryRow(ctx, getWxMPAccountByOpenID, mpOpenid)
	var i WxMpAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MpOpenid,
		&i.Unionid,
		&i.Nickname,
		&i.Avatar,
		&i.Subscribed,
		&i.SubscribeTime,
		&i.LastInteractTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWxMPAccountByUnionID = `-- name: GetWxMPAccountByUnionID :one
SELECT id, user_id, mp_openid, unionid, nickname, avatar, subscribed, subscribe_time, last_interact_time, created_at, updated_at
FROM wx_mp_accounts
WHERE unionid = $1
`

func (q *Queries) GetWxMPAccountByUnionID(ctx context.Context, unionid pgtype.Text) (WxMpAccount, error) {
	row := q.db.QueryRow(ctx, getWxMPAccountByUnionID, unionid)
	var i WxMpAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MpOpenid,
		&i.Unionid,
		&i.Nickname,
		&i.Avatar,
		&i.Subscribed,
		&i.SubscribeTime,
		&i.LastInteractTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWxMPAccountByUserID = `-- name: GetWxMPAccountByUserID :one
SELECT id, user_id, mp_openid, unionid, nickname, avatar, subscribed, subscribe_time, last_interact_time, created_at, updated_at
FROM wx_mp_accounts
WHERE user_id = $1
`

func (q *Queries) GetWxMPAccountByUserID(ctx context.Context, userID pgtype.Text) (WxMpAccount, error) {
	row := q.db.QueryRow(ctx, getWxMPAccountByUserID, userID)
	var i WxMpAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MpOpenid,
		&i.Unionid,
		&i.Nickname,
		&i.Avatar,
		&i.Subscribed,
		&i.SubscribeTime,
		&i.LastInteractTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkWxMPAccountByUnionID = `-- name: LinkWxMPAccountByUnionID :exec
UPDATE wx_mp_accounts
SET user_id = $2, updated_at = now()
WHERE unionid = $1 AND user_id IS NULL
`

type LinkWxMPAccountByUnionIDParams struct {
	Unionid pgtype.Text `json:"unionid"`
	UserID  pgtype.Text `json:"userId"`
}

func (q *Queries) LinkWxMPAccountByUnionID(ctx context.Context, arg LinkWxMPAccountByUnionIDParams) error {
	_, err := q.db.Exec(ctx, linkWxMPAccountByUnionID, arg.Unionid, arg.UserID)
	return err
}

const touchWxMPAccountInteractTime = `-- name: TouchWxMPAccountInteractTime :exec
UPDATE wx_mp_accounts
SET last_interact_time = now(), updated_at = now()
WHERE mp_openid = $1
`

func (q *Queries) TouchWxMPAccountInteractTime(ctx context.Context, mpOpenid string) error {
	_, err := q.db.Exec(ctx, touchWxMPAccountInteractTime, mpOpenid)
	return err
}

const updateWxMPAccountSubscribeStatus = `-- name: UpdateWxMPAccountSubscribeStatus :exec
UPDATE wx_mp_accounts
SET subscribed = $2, updated_at = now()
WHERE mp_openid = $1
`

type UpdateWxMPAccountSubscribeStatusParams struct {
	MpOpenid   string `json:"mpOpenid"`
	Subscribed bool   `json:"subscribed"`
}

func (q *Queries) UpdateWxMPAccountSubscribeStatus(ctx context.Context, arg UpdateWxMPAccountSubscribeStatusParams) error {
	_, err := q.db.Exec(ctx, updateWxMPAccountSubscribeStatus, arg.MpOpenid, arg.Subscribed)
	return err
}

const upsertWxMPAccount = `-- name: UpsertWxMPAccount :one
INSERT INTO wx_mp_accounts (
    id, user_id, mp_openid, unionid, nickname, avatar, subscribed, subscribe_time, last_interact_time, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
ON CONFLICT (mp_openid)
DO UPDATE SET
    user_id = COALESCE(EXCLUDED.user_id, wx_mp_accounts.user_id),
    unionid = COALESCE(EXCLUDED.unionid, wx_mp_accounts.unionid),
    nickname = COALESCE(EXCLUDED.nickname, wx_mp_accounts.nickname),
    avatar = COALESCE(EXCLUDED.avatar, wx_mp_accounts.avatar),
    subscribed = EXCLUDED.subscribed,
    subscribe_time = EXCLUDED.subscribe_time,
    last_interact_time = EXCLUDED.last_interact_time,
    updated_at = now()
RETURNING id, user_id, mp_openid, unionid, nickname, avatar, subscribed, subscribe_time, last_interact_time, created_at, updated_at
`

type UpsertWxMPAccountParams struct {
	ID               string             `json:"id"`
	UserID           pgtype.Text        `json:"userId"`
	MpOpenid         string             `json:"mpOpenid"`
	Unionid          pgtype.Text        `json:"unionid"`
	Nickname         pgtype.Text        `json:"nickname"`
	Avatar           pgtype.Text        `json:"avatar"`
	Subscribed       bool               `json:"subscribed"`
	SubscribeTime    pgtype.Timestamptz `json:"subscribeTime"`
	LastInteractTime pgtype.Timestamptz `json:"lastInteractTime"`
}

func (q *Queries) UpsertWxMPAccount(ctx context.Context, arg UpsertWxMPAccountParams) (WxMpAccount, error) {
	row := q.db.QueryRow(ctx, upsertWxMPAccount,
		arg.ID,
		arg.UserID,
		arg.MpOpenid,
		arg.Unionid,
		arg.Nickname,
		arg.Avatar,
		arg.Subscribed,
		arg.SubscribeTime,
		arg.LastInteractTime,
	)
	var i WxMpAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MpOpenid,
		&i.Unionid,
		&i.Nickname,
		&i.Avatar,
		&i.Subscribed,
		&i.SubscribeTime,
		&i.LastInteractTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
